TRAIN:
  ENABLE: True
  DATASET: hmdb
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
NUM_GPUS: 8
MODEL_PARA:
  CLASSES: 5
DATA:
  SAMPLING_RATE: 4
  NUM_FRAMES: 8
  MEAN: [0.34428156, 0.4120427,0.43003417]
  STD: [0.15653675, 0.1527466, 0.14656885]
LOSS:
  BOX: 0.05
  CLS: 2.0
  OBJ: 1.0
SOLVER:
  MAX_EPOCH: 100