TRAIN:
  ENABLE: True
  DATASET: jhmdb
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
NUM_GPUS: 1
MODEL_PARA:
  CLASSES: 21
DATA:
  SAMPLING_RATE: 4
  NUM_FRAMES: 8
  MEAN: [0.35607178, 0.41034688,0.40509119]
  STD: [0.14203841, 0.13692028, 0.13158599]
LOSS:
  BOX: 0.05
  CLS: 0.5
  OBJ: 1.0
SOLVER:
  MAX_EPOCH: 300
  BASE_LR: 0.1