TRAIN:
  ENABLE: True
  DATASET: ucf101_24
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
NUM_GPUS: 1
DATA:
  SAMPLING_RATE: 2
  NUM_FRAMES: 32
  MEAN: [0.4192, 0.4426, 0.4395]
  STD: [0.1403, 0.1238, 0.1247]
  KEY_FRAME: 1
LOSS:
  BOX: 0.05
  CLS: 0.7
  OBJ: 1.0
SOLVER:
  MAX_EPOCH: 50
  BASE_LR: 0.01